In [1]:
import csv
import matplotlib.pyplot as plt
import requests
import pandas as pd
import json
import os

# Load JSON
filepath = os.path.join("Data", "CIA_WFB.json")
with open(filepath) as jsonfile:
    CIA_WFB = json.load(jsonfile)

In [2]:
CIA_WFB.keys()
CIA_WFB["countries"].keys()

dict_keys(['world', 'afghanistan', 'akrotiri', 'albania', 'algeria', 'american_samoa', 'andorra', 'angola', 'anguilla', 'antarctica', 'antigua_and_barbuda', 'arctic_ocean', 'argentina', 'armenia', 'aruba', 'ashmore_and_cartier_islands', 'atlantic_ocean', 'australia', 'austria', 'azerbaijan', 'bahamas_the', 'bahrain', 'bangladesh', 'barbados', 'belarus', 'belgium', 'belize', 'benin', 'bermuda', 'bhutan', 'bolivia', 'bosnia_and_herzegovina', 'botswana', 'bouvet_island', 'brazil', 'british_indian_ocean_territory', 'british_virgin_islands', 'brunei', 'bulgaria', 'burkina_faso', 'burma', 'burundi', 'cabo_verde', 'cambodia', 'cameroon', 'canada', 'cayman_islands', 'central_african_republic', 'chad', 'chile', 'china', 'christmas_island', 'clipperton_island', 'cocos_keeling_islands', 'colombia', 'comoros', 'congo_democratic_republic_of_the', 'congo_republic_of_the', 'cook_islands', 'coral_sea_islands', 'costa_rica', "cote_d'_ivoire", 'croatia', 'cuba', 'curacao', 'cyprus', 'czechia', 'denmark', 'dhekelia', 'djibouti', 'dominica', 'dominican_republic', 'ecuador', 'egypt', 'el_salvador', 'equatorial_guinea', 'eritrea', 'estonia', 'ethiopia', 'falkland_islands_islas_malvinas', 'faroe_islands', 'fiji', 'finland', 'france', 'french_polynesia', 'gabon', 'gambia_the', 'gaza_strip', 'georgia', 'germany', 'ghana', 'gibraltar', 'greece', 'greenland', 'grenada', 'guam', 'guatemala', 'guernsey', 'guinea', 'guinea_bissau', 'guyana', 'haiti', 'heard_island_and_mcdonald_islands', 'holy_see_vatican_city', 'honduras', 'hong_kong', 'hungary', 'iceland', 'india', 'indian_ocean', 'indonesia', 'iran', 'iraq', 'ireland', 'isle_of_man', 'israel', 'italy', 'jamaica', 'jan_mayen', 'japan', 'jersey', 'jordan', 'kazakhstan', 'kenya', 'kiribati', 'korea_north', 'korea_south', 'kosovo', 'kuwait', 'kyrgyzstan', 'laos', 'latvia', 'lebanon', 'lesotho', 'liberia', 'libya', 'liechtenstein', 'lithuania', 'luxembourg', 'macau', 'macedonia', 'madagascar', 'malawi', 'malaysia', 'maldives', 'mali', 'malta', 'marshall_islands', 'mauritania', 'mauritius', 'mexico', 'micronesia_federated_states_of', 'moldova', 'monaco', 'mongolia', 'montenegro', 'montserrat', 'morocco', 'mozambique', 'namibia', 'nauru', 'navassa_island', 'nepal', 'netherlands', 'new_caledonia', 'new_zealand', 'nicaragua', 'niger', 'nigeria', 'niue', 'norfolk_island', 'northern_mariana_islands', 'norway', 'oman', 'pacific_ocean', 'pakistan', 'palau', 'panama', 'papua_new_guinea', 'paracel_islands', 'paraguay', 'peru', 'philippines', 'pitcairn_islands', 'poland', 'portugal', 'puerto_rico', 'qatar', 'romania', 'russia', 'rwanda', 'saint_barthelemy', 'saint_helena_ascension_and_tristan_da_cunha', 'saint_kitts_and_nevis', 'saint_lucia', 'saint_martin', 'saint_pierre_and_miquelon', 'saint_vincent_and_the_grenadines', 'samoa', 'san_marino', 'sao_tome_and_principe', 'saudi_arabia', 'senegal', 'serbia', 'seychelles', 'sierra_leone', 'singapore', 'sint_maarten', 'slovakia', 'slovenia', 'solomon_islands', 'somalia', 'south_africa', 'southern_ocean', 'south_georgia_and_south_sandwich_islands', 'south_sudan', 'spain', 'spratly_islands', 'sri_lanka', 'sudan', 'suriname', 'svalbard', 'swaziland', 'sweden', 'switzerland', 'syria', 'taiwan', 'tajikistan', 'tanzania', 'thailand', 'timor_leste', 'togo', 'tokelau', 'tonga', 'trinidad_and_tobago', 'tunisia', 'turkey', 'turkmenistan', 'turks_and_caicos_islands', 'tuvalu', 'uganda', 'ukraine', 'united_arab_emirates', 'united_kingdom', 'united_states', 'uruguay', 'uzbekistan', 'vanuatu', 'venezuela', 'vietnam', 'virgin_islands', 'wake_island', 'wallis_and_futuna', 'west_bank', 'western_sahara', 'yemen', 'zambia', 'zimbabwe', 'european_union'])

In [17]:
country_list = []
size_list = []
climate_list = []
pop_list = []
median_age_list = []
urbanization_list = []
life_exp_list = []
drinking_water_source_list = []
roadways_rank_list = []


countries = ["ethiopia", "germany", "japan", "kenya", "uganda", "united_states", "united_kingdom"]

for country in countries:
        
    data = CIA_WFB["countries"][country]
    
  
    country_list.append((data['data']['name']))
    size_list.append((data['data']['geography']['area']['comparative']))
    climate_list.append((data['data']['geography']['climate']))
    pop_list.append((data['data']['people']['population']['total']))
    median_age_list.append((data['data']['people']['median_age']['total']['value']))
    urbanization_list.append((data['data']['people']['urbanization']['urban_population']['value']))
    life_exp_list.append((data['data']['people']['life_expectancy_at_birth']['total_population']['value']))
    drinking_water_source_list.append((data['data']['people']['drinking_water_source']['improved']['total']['value']))
    roadways_rank_list.append((data['data']['transportation']['roadways']['global_rank']))

In [18]:
country_info_df = pd.DataFrame({'country':country_list, 
                                'size':size_list, 
                                'climate':climate_list, 
                                'population':pop_list, 
                                'median_age':median_age_list, 
                                'urbanization':urbanization_list,
                                'life_expectancy':life_exp_list,
                                'drinking_water_source':drinking_water_source_list,
                                'roads_global_rank':roadways_rank_list, 
    
})
country_info_df

,country,size,climate,population,median_age,urbanization,life_expectancy,drinking_water_source,roads_global_rank
0,Ethiopia,slightly less than twice the size of Texas,tropical monsoon with wide topographic-induced...,102374044,17.8,19.5,62.2,57.3,44
1,Germany,three times the size of Pennsylvania; slightly...,"temperate and marine; cool, cloudy, wet winter...",80722792,46.8,75.3,80.7,100.0,12
2,Japan,slightly smaller than California,varies from tropical in south to cool temperat...,126702133,46.9,93.5,85.0,100.0,6
3,Kenya,five times the size of Ohio; slightly more tha...,varies from tropical along coast to arid in in...,46790758,19.5,25.6,64.0,63.2,32
4,Uganda,slightly more than two times the size of Penns...,tropical; generally rainy with two dry seasons...,38319241,15.7,16.1,55.4,79.0,109
5,United States,about half the size of Russia; about three-ten...,"mostly temperate, but tropical in Hawaii and F...",323995528,37.9,81.6,79.8,99.2,1
6,United Kingdom,twice the size of Pennsylvania; slightly small...,temperate; moderated by prevailing southwest w...,64430428,40.5,82.6,80.7,100.0,18